version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  scraper:
    build: .
    container_name: scraper
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/logs
    environment:
      - MONGO_URI=mongodb://mongo:27017

volumes:
  mongo-data:
